### ISSUE TITLE
Failed to find any forward convolution algorithm.

### ISSUE THREAD

**Issue by zhangboshen** [610265158/tinymind_competition#1]
你好，我在跑你的代码（train.sh）的时候（前面几步都i没问题）出现了这个问题，想请教一下您这是什么问题：
`bash ./train.sh
/home/zhangboshen/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from float to np.floating is deprecated. In future, it will be treated as np.float64 == np.dtype(float).type.
  from ._conv import register_converters as _register_converters
2018-05-04 20:02:23,828 Using 1 threads for decoding...
2018-05-04 20:02:23,829 Set enviroment variable MXNET_CPU_WORKER_NTHREADS to a larger number to use more threads.
2018-05-04 20:02:23,829 ImageIter: loading image list /dataspace/zhangboshen/TMDChineseFont/train.lst...
2018-05-04 20:02:27,400 Using 1 threads for decoding...
2018-05-04 20:02:27,400 Set enviroment variable MXNET_CPU_WORKER_NTHREADS to a larger number to use more threads.
2018-05-04 20:02:27,401 ImageIter: loading image list /dataspace/zhangboshen/TMDChineseFont/val.lst...
finetune from pretrained model ...with resnext-50
[20:02:28] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[20:02:28] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
2018-05-04 20:02:28,346 Freezed parameters: [conv0_weight,stage1_unit1_conv1_weight,stage1_unit1_bn1_gamma,stage1_unit1_bn1_beta,stage1_unit1_conv2_weight,stage1_unit1_bn2_gamma,stage1_unit1_bn2_beta,stage1_unit1_conv3_weight,stage1_unit1_bn3_gamma,stage1_unit1_bn3_beta,stage1_unit1_sc_weight,stage1_unit1_sc_bn_gamma,stage1_unit1_sc_bn_beta,stage1_unit2_conv1_weight,stage1_unit2_bn1_gamma,stage1_unit2_bn1_beta,stage1_unit2_conv2_weight,stage1_unit2_bn2_gamma,stage1_unit2_bn2_beta,stage1_unit2_conv3_weight,stage1_unit2_bn3_gamma,stage1_unit2_bn3_beta,stage1_unit3_conv1_weight,stage1_unit3_bn1_gamma,stage1_unit3_bn1_beta,stage1_unit3_conv2_weight,stage1_unit3_bn2_gamma,stage1_unit3_bn2_beta,stage1_unit3_conv3_weight,stage1_unit3_bn3_gamma,stage1_unit3_bn3_beta]
[20:02:31] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:107: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
Traceback (most recent call last):
  File "train.py", line 151, in <module>
    fit(new_sym, new_args, aux_params, train_iter, val_iter, args.batch_size,num_gpus=1)
  File "train.py", line 135, in fit
    eval_metric=acc)
  File "/home/zhangboshen/anaconda3/lib/python3.6/site-packages/mxnet/module/base_module.py", line 520, in fit
    self.update_metric(eval_metric, data_batch.label)
  File "/home/zhangboshen/anaconda3/lib/python3.6/site-packages/mxnet/module/module.py", line 757, in update_metric
    self._exec_group.update_metric(eval_metric, labels)
  File "/home/zhangboshen/anaconda3/lib/python3.6/site-packages/mxnet/module/executor_group.py", line 616, in update_metric
    eval_metric.update_dict(labels_, preds)
  File "/home/zhangboshen/anaconda3/lib/python3.6/site-packages/mxnet/metric.py", line 132, in update_dict
    self.update(label, pred)
  File "/home/zhangboshen/anaconda3/lib/python3.6/site-packages/mxnet/metric.py", line 490, in update
    pred_label = numpy.argsort(pred_label.asnumpy().astype('float32'), axis=1)
  File "/home/zhangboshen/anaconda3/lib/python3.6/site-packages/mxnet/ndarray/ndarray.py", line 1890, in asnumpy
    ctypes.c_size_t(data.size)))
  File "/home/zhangboshen/anaconda3/lib/python3.6/site-packages/mxnet/base.py", line 149, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [20:02:33] src/operator/nn/./cudnn/cudnn_convolution-inl.h:744: Failed to find any forward convolution algorithm.

Stack trace returned 10 entries:
[bt] (0) /home/zhangboshen/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x31fe72) [0x7fc958e1de72]
[bt] (1) /home/zhangboshen/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x320448) [0x7fc958e1e448]
[bt] (2) /home/zhangboshen/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x3161b38) [0x7fc95bc5fb38]
[bt] (3) /home/zhangboshen/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x3163245) [0x7fc95bc61245]
[bt] (4) /home/zhangboshen/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x31642f6) [0x7fc95bc622f6]
[bt] (5) /home/zhangboshen/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x316d7b9) [0x7fc95bc6b7b9]
[bt] (6) /home/zhangboshen/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2a73d10) [0x7fc95b571d10]
[bt] (7) /home/zhangboshen/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2a7c120) [0x7fc95b57a120]
[bt] (8) /home/zhangboshen/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2a5d204) [0x7fc95b55b204]
[bt] (9) /home/zhangboshen/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2a60eab) [0x7fc95b55eeab]
`

**Comment by 610265158** [comment]
Its a problem about cuda and cudnn version,

the environment of mine: ubuntu16.04, mxnet1.2 cuda9, cudnn7

: )
